#
# Copyright (c) 2021, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# SPDX-License-Identifier: MPL-2.0
#

# include: CIM16-update.sparql

# query: boundaryNodes
# All pairs (Connectiviy Node, Topological Node) from a graph that has a modeProfile EquipmentBoundary-
# We expect all Connectivity Nodes have 1 and only one corresponding TopologicalNode
prefix md: <http://iec.ch/TC57/61970-552/ModelDescription/1#>
SELECT *
{
GRAPH ?graphBDEQ {
    ?FullModel md:Model.profile ?modelProfile .
    FILTER (regex(?modelProfile, "EquipmentBoundary-", "i"))
    ?ConnectivityNode
        a cim:ConnectivityNode ;
        cim:IdentifiedObject.name ?name ;
        cim:ConnectivityNode.ConnectivityNodeContainer ?container .
    ?BoundaryPoint
        a eu:BoundaryPoint ;
        eu:BoundaryPoint.ConnectivityNode ?ConnectivityNode .
    OPTIONAL { ?BoundaryPoint eu:IdentifiedObject.energyIdentCodeEic ?energyIdentCodeEicFromNode }
    OPTIONAL { ?container entsoe:IdentifiedObject.energyIdentCodeEic ?energyIdentCodeEicFromNodeContainer }
    OPTIONAL { ?ConnectivityNode cim:IdentifiedObject.description ?description }
}
OPTIONAL { GRAPH ?grapBDTP {
    ?ConnectivityNode cim:ConnectivityNode.TopologicalNode ?TopologicalNode .
    ?TopologicalNode cim:IdentifiedObject.name ?topologicalNodeName
}}
}

