language: java

dist: trusty

jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}
        github_token:
            secure: ${GITHUB_TOKEN}

before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
- echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust

script:
- mvn --settings travis-maven.xml clean verify -Pjacoco coveralls:report sonar:sonar

# after_success:
# - [[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests --settings travis-maven.xml
