language: java

dist: trusty

jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}
        github_token:
            secure: ${GITHUB_TOKEN}

script:
- mvn clean verify -Dproject.jacoco.destFile=${PWD}/target/jacoco.exec -Pjacoco coveralls:report sonar:sonar
