language: java

dist: trusty
sudo: required

jdk:
- oraclejdk8

addons:
    sonarcloud:
        organization: "powsybl-ci-github"
        token:
            secure: ${SONAR_TOKEN}
        github_token:
            secure: ${GITHUB_TOKEN}

script:
- mvn clean verify -Pjacoco coveralls:report sonar:sonar
