/**
 * Copyright (c) 2017-2018, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package com.powsybl.cgmes.conversion;

/**
 * @author Luma Zamarreño <zamarrenolm at aia.es>
 * @author José Antonio Marqués <marquesja at aia.es>
 */
public final class Errors {

    private Errors() {
        // private constructor
    }

    public enum Invalid {
        RTC_MISSING_TRANSFORMER,
        RTC_NOT_SUPPORTED_AT_END_1_OF_XFMR3_REGULATING_CONTROL_ENABLED,
        RTC_IN_RANGE_NEUTRAL_STEP,
        RTC_IN_RANGE_STEP,
        RTC_COULD_NOT_CREATE_RATIO_TAP_CHANGER_ADDER,
        NODE_COUNTRY_ISO_CODES,
        NODE_SV_VOLTAGE,
        AC_DC_CONVERTER_TYPE,
        PTC_NOT_SUPPORTED_FOR_XFMR3,
        PTC_UNEXPECTED_PHASE_TAP_CHANGER_TYPE,
        PTC_NOT_VOLTAGE_STEP_INCREMENT_OUT_OF_PHASE_OR_VOLTAGE_STEP_INCREMENT,
        PTC_IN_RANGE_DEFAULT_STEP,
        PTC_PRESENT_MANDATORY_PROPERTY_TRANSFORMER_WINDING_RATED_U,
        XFMR3_NOT_SUPPORTED_END_POINT_AT_BOUNDARY,
        XFMR3_DIFFERENT_SUBSTATIONS_AT_ENDS,
        DC_LINE_SEGMENT_RATED_UDC,
        DC_LINE_SEGMENT_UNSUPPORTED_MODELING,
        XFMR2_UNSUPPORTED_MODELING_TWO_RTC,
        XFMR2_UNSUPPORTED_MODELING_TWO_PTC,
        XFMR2_RTC_AND_PTC_ON_DIFFERENT_WINDING,
        ABSTRACT_BRANCH_NODE_ON_BOUNDARY,
        ABSTRACT_BRANCH_NO_R_X,
        CONVERSION_XFMR_ONLY_2_OR_3_ENDS_ARE_SUPPORTED,
        DC_MAPPING_HV_DC_CONVERTER_STATION,
        DC_MAPPING_REASSIGN_DIFFERENT_VALUES,
        EQUIVALENT_BRANCH_ASYMMETRICAL_IMPEDANCE
    }

    public enum Ignored {
        RTC_NOT_SUPPORTED_AT_END_1_OF_XFMR3_NEUTRAL_STEP_AND_REGULATING_CONTROL_DISABLED,
        RTC_UNSUPPORTED_REGULATION_MODE,
        RTC_REGULATING_CONTROL_BAD_TARGET_VOLTAGE,
        PTC_NOT_SUPPORTED_FOR_XFMR3,
        PTC_INCONSISTENT_X_STEP_MIN_X_STEP_MAX,
        PTC_UNSUPPORTED_REGULATION_MODE,
        OPERATIONAL_LIMIT_PATL,
        OPERATIONAL_LIMIT_CURRENT_LIMIT,
        STATIC_VAR_COMPENSATOR_SLOPE,
        SWITCH_SAME_END_BUSES
    }

    public enum Missing {
        ABSTRACT_IDENTIFIED_NAME,
        VOLTAGE_LEVEL_SUBSTATION,
        VOLTAGE_LEVEL_BASE_VOLTAGE,
        NODE_VOLTAGE_LEVEL,
        OPERATIONAL_LIMIT_EQUIPMENT,
        OPERATIONAL_LIMIT_TERMINAL,
        AC_LINE_SEGMENT_NODE_ID,
        AC_LINE_SEGMENT_EQUIPMENT_AT_BOUNDARY,
        ABSTRACT_CONDUCTING_NODE_ID,
        ABSTRACT_CONDUCTING_VOLTAGE_LEVEL,
        DC_LINE_SEGMENT_CONVERTER,
        DC_LINE_SEGMENT_MAX_P,
        DC_LINE_SEGMENT_ACTIVE_POWER_SETPOINT,
        PTC_POWER_TRANSFORMER,
        PTC_PHASE_TAP_CHANGER_TABLE,
        PTC_PHASE_TAP_CHANGER_TABLE_POINTS,
        PTC_WINDING_CONNECTION_ANGLE,
        RTC_RATIO_TAP_CHANGER_TABLE,
        RTC_RATIO_TAP_CHANGER_TABLE_POINTS
    }

    public enum Fixes {
        ABSTRACT_CONDUCTING_REACTIVE_LIMITS,
        PTC_PHASE_TAP_CHANGER_TABLE_POINT,
        RTC_RATIO_TAP_CHANGER_TABLE_POINT,
        SWITCH_AS_LOW_IMPEDANCE_LINE,
        DC_LINE_SEGMENT_RESISTANCE,
        REGULATING_CONTROL_TARGET,
        SHUNT_B_PER_SECTION,
        EQUIVALENT_INJECTION_REGULATION_TARGET
    }

    public enum Pending {
        DC_LINE_SEGMENT_CONVERTERS_MODES,
        OPERATIONAL_LIMIT_LIMIT_NOT_ASSIGNED
    }
}
