@startuml

namespace existing {

class OperatorStrategy {
  - String id
  - ContingencyContext contingencyContext
  - List<ConditionalActions> conditionalActions
}
OperatorStrategy --* "1" ContingencyContext
OperatorStrategy --* "*" ConditionalActions

interface Condition

class ConditionalActions {
  - List<String> actionIds
  - Condition condition
}
ConditionalActions ..* "*" Action
ConditionalActions --* "1" Condition

class ContingencyContext {
  - ContingencyContextType contextType
  - Optional<Integer> applicationDelay
}
ContingencyContext --* "1" ContingencyContextType

note left of ContingencyContext::applicationDelay
  new field
end note

enum ContingencyContextType {
  ALL
  NONE
  SPECIFIC
  ONLY_CONTINGENCIES
}

interface Action {
  + getId()
  + getType()
  + NetworkModification toModification()
}

}

Condition <|-- AndCondition
Condition <|-- OrCondition
Condition <|-- AnyViolationInCountryCondition

class AndCondition {
  + Set<Condition> conditions
}

class OrCondition {
  + Set<Condition> conditions
}

class AnyViolationInCountryCondition {
 + Country country
 + Set<LimitViolationType> conditionFilters
}
note bottom: condition filter or branch threshold ?

class OptimizableRemedialAction {
  - String id
  - Condition condition
  - ContingencyContext contingencyContext
}
OptimizableRemedialAction --* "1" Condition
OptimizableRemedialAction --* "1" ContingencyContext
OptimizableRemedialAction <|-- BinaryRemedialAction
OptimizableRemedialAction <|-- RangeRemedialAction

class BinaryRemedialAction {
  - Set<Action> actions
  + Set<Action> toActions()
  + OperatorStrategy toOperatorStrategy()
}
BinaryRemedialAction --* "*" Action

class RangeRemedialAction {
  - Set<RangeAction> rangeActions
  + RangeType rangeType
  + Set<Action> toActions(double setPoint)
  + OperatorStrategy toOperatorStrategy(double setPoint)
}
RangeRemedialAction --* "*" RangeAction
RangeRemedialAction --* "1" RangeType

enum RangeType {
  DISCRETE
  CONTINUOUS
}

interface RangeAction {
  + Action toAction(double setPoint)
}
note bottom: Clone of actions but without "set point"

class ExclusiveOptimizableRemedialActionGroup {
  - List<String> exclusiveRemedialActionIds
  - int limitOfSelectedRemedialActions
}
ExclusiveOptimizableRemedialActionGroup ..* "*" OptimizableRemedialAction

class TemporalRangeRemedialAction {
  - Map<ZonedDateTime, RangeRemedialAction> rangeRemedialActionsPerCaseDate
  + Set<Action> toActions(ZonedDateTime caseDate, double setPoint)
  + OperatorStrategy toOperatorStrategy(ZonedDateTime caseDate, double setPoint)
  + Map<ZonedDateTime, Set<Action>> toActions(Map<ZonedDateTime, Double> setPoints)
  + Map<ZonedDateTime, OperatorStrategy> toOperatorStrategy(Map<ZonedDateTime, Double> setPoint)
}
TemporalRangeRemedialAction --* "*" RangeRemedialAction
TemporalRangeRemedialAction -|> OptimizableRemedialAction



@enduml