@startuml

'namespace mvp {

namespace existing {

class OperatorStrategy {
  - String id
  - ContingencyContext contingencyContext
  - List<ConditionalActions> conditionalActions
}
OperatorStrategy --* "1" ContingencyContext
OperatorStrategy --* "*" ConditionalActions

class ConditionalActions {
  - List<String> actionIds
  - Condition condition
  - Optional<Integer> applicationDelay
}
ConditionalActions ..* "*" Action
ConditionalActions --* "1" Condition
note right of ConditionalActions::applicationDelay
  new field
end note

interface Condition
Condition <|-- AndCondition
Condition <|-- OrCondition

class AndCondition {
  + Set<Condition> conditions
}

class OrCondition {
  + Set<Condition> conditions
}

class ContingencyContext {
  - ContingencyContextType contextType
}
ContingencyContext --* "1" ContingencyContextType


enum ContingencyContextType {
  ALL
  NONE
  SPECIFIC
  ONLY_CONTINGENCIES
}

interface Action {
  + getId()
  + getType()
  + NetworkModification toModification()
}

'end namespace existing
}

Condition <|-- AnyViolationInCountryCondition


class AnyViolationInCountryCondition {
 + Country country
 + Set<LimitViolationType> conditionFilters
}
note right: condition filter or branch threshold ?

class OptimizableRemedialAction {
  - String id
  - Condition condition
  - ContingencyContext contingencyContext
  - Optional<Integer> applicationDelay
}
OptimizableRemedialAction --* "1" Condition
OptimizableRemedialAction --* "1" ContingencyContext
OptimizableRemedialAction <|-- BinaryRemedialAction
OptimizableRemedialAction <|-- RangeRemedialAction

class BinaryRemedialAction {
  - Set<Action> actions
  + Set<Action> toActions()
}
BinaryRemedialAction --* "*" Action

class RangeRemedialAction {
  - Optional<Step> step
  - Range range
  - Set<RangeAction> rangeActions
  + Set<Action> toActions(double setPoint)
}
note bottom
 Questions ouvertes:
  - comment gérer le minimum type puissance min de fonctionnement ?
  => Résolu: avec des unions
end note
RangeRemedialAction --* "*" RangeAction
RangeRemedialAction --* "1" Range
RangeRemedialAction --* "1" Step
note left of RangeRemedialAction::step
 Lié à l'optimisation
 Exemple: Counter-trading par pas de 100 MW
end note

interface Range{
}
note bottom
  Pas évident comment le rendre user friendly ?
  Est-ce qu'il est mieux de laisser parcourir l'arbre des ranges par l'optim ?
  On peut simplifier ça en interdisant l'union et avec les exclusivités entre parades
  Méthodes niceToHave:
 + UnionRange toUnionOfAbsoluteContinuousRanges(double initialSetPoint)
 + isValidSetpoint(double setPoint, double initialSetPoint)
end note
Range <|-- ContinuousRange
Range <|-- IntersectionRange
Range <|-- UnionRange

interface ContinuousRange {
 - boolean isRelative
 - Optional<Double> mimimum
 - Optional<Double> maximum
}
note left of Range::isRelative
 Notion similaire
 Mais valeur différente de isRelativeValue dans les actions
end note

class IntersectionRange {
 - Set<Range> ranges
}

class UnionRange {
 - Set<Range> ranges
}

class Step {
 - boolean isRelative
 - double value
 - double offset = 0
}

interface RangeAction {
  - boolean isIntegerValue
  + Action toAction(double setPoint)
}
note left of RangeAction::isIntegerValue
 Lié à la physique
 Exemple: PST
end note
'note bottom: Clone of some actions but without "set point"

interface DiscreteRangeAction {
}
DiscreteRangeAction --|> RangeAction

class AbstractTapChangerRegulationAction {

}
PhaseTapChangerTapPositionRangeAction --|> DiscreteRangeAction

interface ContinuousRangeAction {
}
ContinuousRangeAction --|> RangeAction

class LoadRangeAction {
 - double pMin
 - double pMax
 + LoadAction toAction(double setPoint)
}
LoadRangeAction --|> ContinuousRangeAction




interface SetpointBasedAction {
}
SetpointBasedAction --|> Action

class AbstractLoadAction {
}
AbstractLoadAction --|> SetpointBasedAction

class MultipleActionWithKey {
}
MultipleActionWithKey --|> SetpointBasedAction
'end namespace mvp
'}

namespace niceToHave {
class ExclusiveOptimizableRemedialActionGroup {
  - List<String> exclusiveRemedialActionIds
  - int limitOfSelectedRemedialActions
}
ExclusiveOptimizableRemedialActionGroup ..* "*" OptimizableRemedialAction

class TemporalRangeRemedialAction {
  - Set<TemporalRangeAction> temporalRangeActions
  + Set<Action> toActions(ZonedDateTime caseDate, double setPoint)
}
TemporalRangeRemedialAction --* "*" TemporalRangeAction
TemporalRangeRemedialAction --|> OptimizableRemedialAction

interface TemporalRangeAction {
    + Action toAction(ZonedDateTime caseDate, double setPoint)
}
note right: Clone of some range actions but with a case date
}


@enduml