@startuml


namespace existing {

class OperatorStrategy {
  - String id
  - ContingencyContext contingencyContext
  - List<ConditionalActions> conditionalActions
}
OperatorStrategy --* "1" ContingencyContext
OperatorStrategy --* "*" ConditionalActions

class ConditionalActions {
  - List<String> actionIds
  - Condition condition
  - Optional<Integer> applicationDelay
}
ConditionalActions ..* "*" Action
ConditionalActions --* "1" Condition
note right of ConditionalActions::applicationDelay
  new field
end note

interface Condition
Condition <|-- AndCondition
Condition <|-- OrCondition

class AndCondition {
  + Set<Condition> conditions
}

class OrCondition {
  + Set<Condition> conditions
}

class ContingencyContext {
  - ContingencyContextType contextType
}
ContingencyContext --* "1" ContingencyContextType


enum ContingencyContextType {
  ALL
  NONE
  SPECIFIC
  ONLY_CONTINGENCIES
}

interface Action {
  + getId()
  + getType()
  + NetworkModification toModification()
}

'end namespace existing
}

Condition <|-- AnyViolationInCountryCondition


class AnyViolationInCountryCondition {
 + Country country
 + Set<LimitViolationType> conditionFilters
}
note right: condition filter or branch threshold ?

class OptimizableRemedialAction {
  - String id
  - Condition condition
  - ContingencyContext contingencyContext
  - Optional<Integer> applicationDelay
  - Optional<ExtraTemporalContraints> extraTemporalContraints
}
OptimizableRemedialAction --* "1" Condition
OptimizableRemedialAction --* "1" ContingencyContext
OptimizableRemedialAction <|-- BinaryRemedialAction
OptimizableRemedialAction <|-- RangeRemedialAction

class BinaryRemedialAction {
  - Set<Action> actions
  + Set<Action> toActions()
}
BinaryRemedialAction --* "*" Action

class RangeRemedialAction {
  - Optional<Step> step
  - Range range
  - Map<RangeAction, double> rangeActionsAndKeys
  + Set<Action> toActions(double setPoint)
}
RangeRemedialAction --* "*" RangeAction
RangeRemedialAction --* "1" Range
RangeRemedialAction --* "1" Step
note right of RangeRemedialAction::step
 Lié à l'optimisation
end note

interface Range{
}
note bottom
  Pas évident comment le rendre user friendly ?
  Est-ce qu'il est mieux de laisser parcourir l'arbre des ranges par l'optim ?
  On peut simplifier ça en interdisant l'union et avec les exclusivités entre parades
  Méthodes niceToHave:
 + UnionRange toUnionOfAbsoluteContinuousRanges(double initialSetPoint)
 + isValidSetpoint(double setPoint, double initialSetPoint)
end note
Range <|-- ContinuousRange
Range <|-- IntersectionRange
Range <|-- UnionRange

interface ContinuousRange {
 - boolean isRelative
 - Optional<Double> mimimum
 - Optional<Double> maximum
}
note left of Range::isRelative
 Notion similaire
 Mais valeur différente de isRelativeValue dans les actions
end note

class IntersectionRange {
 - Set<Range> ranges
}

class UnionRange {
 - Set<Range> ranges
}

class Step {
 - boolean isRelative
 - double value
 - double offset = 0
}

interface RangeAction {
  - boolean isIntegerValue
  + Action toAction(double setPoint)
}
note bottom: Clone of "set point based actions" but without "set point"
note left of RangeAction::isIntegerValue
 Lié à la physique
end note

PhaseTapChangerTapPositionRangeAction --|> RangeAction

class LoadRangeAction {
 + LoadAction toAction(double setPoint)
}
LoadRangeAction --|> RangeAction

class ExclusiveOptimizableRemedialActionGroup {
  - List<String> exclusiveRemedialActionIds
  - int limitOfSelectedRemedialActions
}
ExclusiveOptimizableRemedialActionGroup ..* "*" OptimizableRemedialAction

class ExtraTemporalContraints {
  - SimpleContraints simpleContraints
  - List<BudgetContraint> budgetContraints
  - VariableConstraints variableConstraints
}
ExtraTemporalContraints "0..1" *-- OptimizableRemedialAction
ExtraTemporalContraints --* "1" SimpleContraints
ExtraTemporalContraints --* "*" BudgetContraint
ExtraTemporalContraints --* "1" VariableConstraints

class SimpleContraints {
  - int levelTime // Durée de palier
  - int minStopTime // Durée arrêt min
  - int minRunTime // Durée marche min
  - int minBalancingTime // Durée min ajustement DOmin
  - int minStartBalancingTime // Durée min ajustement démarrage
  - int maxBalancingTime // Durée max ajustement
  - int noBalancingTime // Durée de non ajustement DNA
  - double constantUpGradient
  - double constantDownGradient
}

class BudgetContraint {
  - ZonedDateTime startTime
  - ZonedDateTime endTime
  - double value
  - BudgetType type
}
BudgetContraint --* "1" BudgetType

enum BudgetType {
  MAX_BALANCING_NUMBER // Nombre d'activation max
  MAX_BALANCING_TIME // Temps d'activation max
  MAX_ENERGY
  MIN_ENERGY
  MAX_RUN_TIME
  MAX_STARTUPS
}

class VariableConstraints {
  - List<ZonedDateTime> dates
  - List<range> variationRange // Pmin, Pmax, maxChange and minChange
  - List<int> mobilisationTime // Durée de mobilisation DMO
  - List<int> delayTime // Durée de prévenance DP
  - List<int> lagTime // Durée de retour au programme
  - List<boolean> canStartUpShutDownBalancing
}

note right of VariableConstraints::canStartUpShutDownBalancing
  Example: start/end balancing on round hours
end note

@enduml