/**
 * Copyright (c) 2016, All partners of the iTesla project (http://www.itesla-project.eu/consortium)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */
package cim1.model;

import cim1.exc.InterpretationException;
import cim1.exc.LinkageException;
import java.util.BitSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.EnumMap;
import javax.xml.stream.XMLStreamException;
import cim1.CIMURI;
import javax.xml.stream.XMLStreamWriter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * This file has been automatically generated by CIMGateway
 *
 * Description :
 *
 * This class "TopologicalIsland.java" represents the
 * class TopologicalIsland extends IdentifiedObject
 *    + AngleRef_TopologicalNode   0..1   TopologicalNode 
 *    + TopologicalNodes   0..-1   TopologicalNode   (inverseAssociation) 

 */
public class TopologicalIsland extends IdentifiedObject {

    private static Logger LOGGER = LoggerFactory.getLogger(TopologicalIsland.class);

    /**
     * Attribute "angleRef_TopologicalNode"
     *
     * Comment from profile:
     * The angle reference for the island.   Normally there is one TopologicalNode that is selected as the angle reference for each island.   Other reference schemes exist, so the association is optional.
     */
    public TopologicalNode angleRef_TopologicalNode;

    /**
     * The id of the attribute "angleRef_TopologicalNode"
     * This id is mainly used to resolve links after parsing an instance
     */

    public String idAngleRef_TopologicalNode;

    /**
     * Attribute "topologicalNodes"
     *
     * Comment from profile:
     * A topological node belongs to a topological island
     */
    public List<TopologicalNode> topologicalNodes;

    /**
     * The current bitset describing the state of each CIM attribute of this
     * class
     */
    private BitSet currentBitset = new BitSet();

   /**
    * The bitset describing which CIM attributes of this class have to set to
    * be consistent within a "merged" context
    */
    private final BitSet minBitset = new BitSet();

   /**
    * The Map of subset<=>bitset describing which CIM attributes of this class
    * have to set to be consistent within a specific subset context
    */
    private final Map<Subset, BitSet> minBitsets
            = new EnumMap<Subset, BitSet>(Subset.class);

    
    /**
     * Utility to return the "angleRef_TopologicalNode"
     *
     * @return the value of the attribute "angleRef_TopologicalNode"
     */
    public TopologicalNode getAngleRef_TopologicalNode() {
        return this.angleRef_TopologicalNode;
    }

    /**
     * Utility to test if the value of "angleRef_TopologicalNode" has been set
     *
     * @return boolean
     *            if true the attribute "angleRef_TopologicalNode" is already set
     *            if false it isn't yet
     */
    public boolean angleRef_TopologicalNodeIsSet() {
        return this.currentBitset.get(0);
    }

    /**
     * Utility to set the "angleRef_TopologicalNodeValue"
     *
     * @param angleRef_TopologicalNodeValue
     *            instance to set
     * @param setInverse
     *            boolean to specify whether to set the inverse association
     *            or not
     * @throws LinkageException
     */
    public void setAngleRef_TopologicalNode(
            TopologicalNode angleRef_TopologicalNodeValue,
            boolean setInverse) throws LinkageException {
        this.angleRef_TopologicalNode = angleRef_TopologicalNodeValue;
        this.currentBitset.set(0);
        if (setInverse) {
            
            if (angleRef_TopologicalNodeValue != null) {
                angleRef_TopologicalNodeValue.setAngleRef_TopologicalIsland(this, false);
            }
        }
    }
  /**
   * Utility to return the "topologicalNodes" List of 
   * "TopologicalNode" enum
   *
   * @return the list of the attributes "topologicalNodes"
   */
    public List<TopologicalNode > getTopologicalNodes() {
        return this.topologicalNodes;
    }

    /**
     * Utility to add a value within the "topologicalNodes" ArrayList of 
     * "TopologicalNode"
     *
     * @param topologicalNodesValue 
     *            value to add within the ArrayList
     * @param setInverse
     *            boolean to specify whether to set the inverse association or not
     * @throws LinkageException
     */
    public void addTopologicalNodes(
            TopologicalNode topologicalNodesValue, 
            boolean setInverse) throws LinkageException {
        
        if (topologicalNodes == null) {
            topologicalNodes = new ArrayList<TopologicalNode>();
        }
        
        this.topologicalNodes.add(topologicalNodesValue);
        this.currentBitset.set(1);
       
        if (setInverse) {
            
            if (topologicalNodesValue != null) {
                topologicalNodesValue.setTopologicalIsland(this, false);
            }
        }
    }

    /**
     * Utility to test if the value of "topologicalNodes" has been set
     *
     * @return boolean
     *            if true the attribute "topologicalNodes" is already set
     *            if false it isn't yet
     */
    public boolean topologicalNodesIsSet() {
        return this.currentBitset.get(1);
    }


    /**
     * Factory of the class
     *
     * @param id
     *            id of the class TopologicalIsland to create
     * @return the class created
     */
    public static TopologicalIsland create(final String id) {
        TopologicalIsland newTopologicalIsland = new TopologicalIsland();
        newTopologicalIsland.setId(id);
        return newTopologicalIsland;
    }

    /**
     * Utility to "clear" the content of a class when a subset is invalidated
     *
     * @param subset subset to clean
     */
    @Override
    public void clearContent(Subset subset) {

        // First of all, we clear the associations:
        this.clearAssociations(subset);

        switch (subset) {
            default: // nothing to clear
        }
    }

    /**
     * Utility to read an attribute
     * This function is called by the CIMModel
     *
     * @param class_name
     *            the read name of class
     * @param attr_name
     *            the read name of attribute
     * @param value
     *            the read value of the attribute
     * @param model
     *            the interface to the model this class belongs to
     * @throws InterpretationException
     */
    @Override
    public void readAttribute(final String class_name, final String attr_name,
                              final String value, CIMModel model) throws InterpretationException {

        if (class_name.equals("TopologicalIsland")) {
                StringBuilder errorMessage = new StringBuilder("The attribute \"");
                errorMessage.append(attr_name);
                errorMessage.append("\" in class \"");
                errorMessage.append(class_name);
                errorMessage
                        .append("\" could not be found in the model !");
                throw new InterpretationException(errorMessage.toString());
            } else {
                // We do not check if we are in the proper subset
                // to call the function on
                // the parent class
                super.readAttribute(class_name, attr_name, value, model);

            }
    }

    /**
     * Utility to read a reference to a resource
     * This function is called by the CIMModel
     *
     * @param class_name
     *            the read name of class
     * @param resource_name
     *            the read name of the associated resource
     * @param id
     *            the id of the associated resource
     * @param model
     *            the model this class belongs to
     * @throws InterpretationException
     */
    @Override
    public void readResource(final String class_name,
            final String resource_name, final String id, CIMModel model)
            throws InterpretationException, LinkageException {
        if (class_name.equals("TopologicalIsland")) {

            if (resource_name.equals("AngleRef_TopologicalNode")) {

                if (!(model.isCurrentSubsetSet())
                        || (model.getCurrentSubset() == Subset.Topology)) {
                    idAngleRef_TopologicalNode = id.substring(1);
                    if (!super.isAddedToUnresolved()) {
                          model.addUnresolved();
                          super.addToUnresolved();
                    }

                    return;
                } else {
                    StringBuilder errorMessage
                            = new StringBuilder("The association \"");
                    errorMessage.append(resource_name);
                    errorMessage.append("\" in class");
                    errorMessage.append("\""+class_name+" \"");
                    errorMessage.append("is not supposed to be in the subset \"");
                    errorMessage.append(model.getCurrentSubset().getIdentifier());
                    errorMessage.append("\"");
                    throw new InterpretationException(errorMessage.toString());
                }
           }

    
            StringBuilder errorMessage = new StringBuilder("The association \"");
            errorMessage.append(resource_name);
            errorMessage.append("\" in class \"");
            errorMessage.append(class_name);
            errorMessage.append("\" could not be found in the model !");
            throw new InterpretationException(errorMessage.toString());
        } else {
            super.readResource(class_name, resource_name, id, model);
        }
    }

    /**
     * Utility to write the content into the CIM XML format
     *
     * @param writeID
     *            specifies whether to write the XML "id" attribute (this is used for describing concrete class)
     * @param xmlsw
     *            XMLStreamWriter where are stored the elements to write
     */
    @Override
    public void write(XMLStreamWriter xmlsw, boolean writeID) {

        /*
         * In previous versions, we used to check the consistency
         * of the instance in the context but this task is now
         * performed by the model before attempting to write.
         * Therefore each instance can now be written even if
         * it is not consistent !
         */

        if (writeID) {

            try {
                xmlsw.writeStartElement(CIMURI.CIMURI, "TopologicalIsland");
                xmlsw.writeAttribute(CIMModel.rdfURI, "ID", getId());
                // xmlsw.writeCharacters("\n");
            } catch (XMLStreamException e) {
                StringBuilder errorMessage = new StringBuilder(
                        "Error while trying to write the class ");
                errorMessage.append("TopologicalIsland ");
                errorMessage.append("which ID has been initialized to : ");
                errorMessage.append(getId());
                LOGGER.error(errorMessage.toString());
                LOGGER.error(e.toString(), e);
            }
        }
        writeClass(xmlsw);
        super.write(xmlsw, false);

        if (writeID) {
            try {
                xmlsw.writeEndElement();
                // xmlsw.writeCharacters("\n");
            } catch (XMLStreamException e) {
                StringBuilder errorMessage = new StringBuilder(
                        "Error while trying to write the end Element of the class ");
                errorMessage.append("TopologicalIsland ");
                errorMessage.append("which ID has been initialized to : ");
                errorMessage.append(getId());
                LOGGER.error(errorMessage.toString());
                LOGGER.error(e.toString(), e);
            }
        }

        return;
    }

    /**
     * Utility to write the content this class into the CIM/XML format according
     * to a subset
     *
     * @param subset
     *            the subset defining the context in which to write this class
     * @param writeID
     *            specifies whether to write the XML "id" attribute (this is used for describing concrete class)
     * @param xmlsw
     *            the stream in which are stored the elements to write
     */
    @Override
    public void write(XMLStreamWriter xmlsw, final Subset subset,
            boolean writeID) {

        /*
         * In previous versions, we used to check the consistency
         * of the instance in the context but this task is now
         * performed by the model before attempting to write.
         * Therefore each instance can now be written even if
         * it is not consistent !
         */

        switch (subset) {
        case Topology: {

            if (writeID) {
                try {
                    xmlsw.writeStartElement(CIMURI.CIMURI, "TopologicalIsland");
                    xmlsw.writeAttribute(CIMModel.rdfURI, "ID", getId());
                    // xmlsw.writeCharacters("\n");
                } catch (XMLStreamException e) {
                    StringBuilder errorMessage = new StringBuilder(
                            "Error while trying to write the class ");
                    errorMessage.append("TopologicalIsland ");
                    errorMessage.append("which ID has been initialized to : ");
                    errorMessage.append(getId());
                    errorMessage.append(" in the subset ");
                    errorMessage.append("Topology");
                   LOGGER.error(errorMessage.toString());
                   LOGGER.error(e.toString(), e);
                }
            }

            writeClass(xmlsw);
            super.write(xmlsw, subset, false);
            if (writeID) {

                try {
                    xmlsw.writeEndElement();
                    // xmlsw.writeCharacters("\n");
                } catch (XMLStreamException e) {
                    StringBuilder errorMessage = new StringBuilder(
                            "Error while trying to write end element of ");
                    errorMessage.append("TopologicalIsland ");
                    errorMessage.append("which ID has been initialized to : ");
                    errorMessage.append(getId());
                    errorMessage.append(" in the subset ");
                    errorMessage.append("Topology");
                    LOGGER.error(errorMessage.toString());
                    LOGGER.error(e.toString(), e);
                }

            }
            break;
        }
        default: {// Do nothing !
        }
        }
        return;
    }

    /**
     * Utility to resolve the links at the end of parsing
     *
     * @param model
     *            the model this class belongs to
     * @param boundaryModel
     *            the model that gather data about the boundarySet, used
     *            as a resource force links resolving
     * @throws Linkage Exception
     */
    @Override
    public void resolveLinks(CIMModel model, CIMModel boundaryModel) throws LinkageException {
        if (idAngleRef_TopologicalNode != null) {
            TopologicalNode attributeToSet =
                    model.searchTopologicalNode
                    (idAngleRef_TopologicalNode);

            if (attributeToSet != null) {
                boolean setInverse = true;

                try {
                    this.setAngleRef_TopologicalNode(attributeToSet, setInverse);
                } catch(LinkageException e) {
                   LOGGER.error(e.toString(), e);
                    throw new LinkageException(e.getMessage());
                }
            } else if (boundaryModel != null) {
                TopologicalNode attributeToSetFromBoundary = boundaryModel.searchTopologicalNode(idAngleRef_TopologicalNode);
                if(attributeToSetFromBoundary != null) {
                    attributeToSetFromBoundary.setFromBoundary(true);
                    try {
                        model.createTopologicalNode(idAngleRef_TopologicalNode, attributeToSetFromBoundary);
                    } catch (InterpretationException e) {
                       LOGGER.error(e.toString(), e);
                    }
                    boolean setInverse = true;
                    try {
                        this.setAngleRef_TopologicalNode(attributeToSetFromBoundary, setInverse);
                    } catch(LinkageException e) {
                       LOGGER.error(e.toString(), e);
                        throw new LinkageException(e.getMessage());
                    }
                    attributeToSetFromBoundary.resolveLinks(model, boundaryModel);
                } else {
                    StringBuilder errorMessage = new StringBuilder(
                            "Could not find the reference to object of type \"TopologicalNode\" and id \"");
                    errorMessage.append(idAngleRef_TopologicalNode);
                    errorMessage.append("\" in \"TopologicalIsland\" of id \"");
                    errorMessage.append(this.getId());
                    errorMessage.append("\" !");
                    throw new LinkageException(errorMessage.toString());
                }
            } else {
                StringBuilder errorMessage = new StringBuilder(
                        "Could not find the reference to object of type \"TopologicalNode\" and id \"");
                errorMessage.append(idAngleRef_TopologicalNode);
                errorMessage.append("\" in \"TopologicalIsland\" of id \"");
                errorMessage.append(this.getId());
                errorMessage.append("\" !");
                throw new LinkageException(errorMessage.toString());
            }
        }



        // TODO : implement vectors (not required according to CIM
        // specifications)
        super.resolveLinks(model, boundaryModel);
        removeFromUnresolved();
    }

    /**
     * Utility to check whether this class is consistent according to a subset
     *
     * @param subset
     *            the subset defining the context in which to check whether this class is consistent
     * @return a ConsistencyCheck instance whose boolean attribute (consistent)
     *         indicates if this class is consistent and whose String attribute
     *         (message)
     *         indicates why this class is not consistent if it is not
     */
    @Override
    public ConsistencyCheck modelConsistency(final Subset subset) {
        BitSet intersection = new BitSet(this.minBitsets.get(subset).length());
        intersection.or(this.minBitsets.get(subset));
        // we create a copy of minBitsets.get(subset)
        intersection.and(this.currentBitset);
        boolean consistent = (this.minBitsets.get(subset).equals(intersection));
        StringBuilder message = new StringBuilder("");

        if (!consistent) {
            message.append(getMessageForConsistency(this.minBitsets.get(subset)));
        }
        // consistent = (super.modelConsistency().getLeft()) ? (consistent &&
        // (true)):(consistent && (false))
        // message.append((super.modelConsistency(subset)).getRight());

        if (super.modelConsistency().isConsistent()) {
            consistent = consistent && (true);
            message.append((super.modelConsistency(subset)).getMessage());
        } else {
            consistent = consistent && (false);
            message.append((super.modelConsistency(subset)).getMessage());
        }

        return new ConsistencyCheck(consistent, message.toString());
    }

    /**
     * Utility to check whether this class is consistent in a "merged" context
     *
     * @return a ConsistencyCheck instance whose boolean attribute (consistent)
     *         indicates if this class is consistent and whose String attribute
     *         (message)
     *         indicates why this class is not consistent if it is not
     */
    @Override
    public ConsistencyCheck modelConsistency() {
        BitSet intersection = new BitSet(this.minBitset.length());
        intersection.or(this.minBitset);
        // we create a copy of minBitSet
        intersection.and(this.currentBitset);
        boolean consistent = (this.minBitset.equals(intersection));
        StringBuilder message = new StringBuilder("");

        if (!consistent) {
        message.append(getMessageForConsistency(this.minBitset));
        }
        // consistent = (super.modelConsistency().getLeft()) ? (consistent &&
        // (true)):(consistent && (false))
        // message += (super.modelConsistency(subset)).getRight();

        if (super.modelConsistency().isConsistent()) {
            consistent = consistent && (true);
            message.append((super.modelConsistency()).getMessage());
        } else {
            consistent = consistent && (false);
            message.append((super.modelConsistency()).getMessage());
        }

        return new ConsistencyCheck(consistent, message.toString());
    }

    /**
     * Utility to copy the "base" of an other instance of the same class
     * This utility does not copy the associations with other instances from
     * the instance to copy
     *
     * @param otherTopologicalIsland
     *            the instance to copy
     */
    public void copyBase(final TopologicalIsland otherTopologicalIsland) {

        // Memory allocation has done successfully !
        // Dropping "old" objects...
        // This part may change : we do nothing to allow the user to access
        // object by their id from the global model.

        if (otherTopologicalIsland.currentBitset.get(0)) {
            TopologicalNode angleRef_TopologicalNodeAssociation = otherTopologicalIsland.getAngleRef_TopologicalNode();

            //this.idAngleRef_TopologicalNode = (angleRef_TopologicalNodeAssociation != null) ? angleRef_TopologicalNodeAssociation.getId() : "";
            if (angleRef_TopologicalNodeAssociation != null) {
                this.idAngleRef_TopologicalNode = angleRef_TopologicalNodeAssociation.getId();
                // the proper bit will be set when the setter is called
            } else {
                this.idAngleRef_TopologicalNode = "";
            }
        }

        // TODO : Call the parent copy constructor instead ?
        super.copyBase(otherTopologicalIsland);

    }

    /**
     * Utility to return the content of this class into the CIM XML format
     *
     * @param xmlsw
     *            the stream in which are stored the elements to write
     */
    private void writeClass(XMLStreamWriter xmlsw) {

        if (currentBitset.get(0)) {

    /*
     * Careful here : we may write an association "twice" if
     * the association is 1..1 one and if
     * both ends belong to the same subset
     */

        if (idAngleRef_TopologicalNode != null &&
                !idAngleRef_TopologicalNode.isEmpty()) {

            try {
                // xmlsw.writeCharacters("\t");
                xmlsw.writeEmptyElement(CIMURI.CIMURI,
                        "TopologicalIsland.AngleRef_TopologicalNode");
                xmlsw.writeAttribute(CIMModel.rdfURI, "resource", "#"
                        + idAngleRef_TopologicalNode);
                // xmlsw.writeCharacters("\n");
            } catch(XMLStreamException e) {
                StringBuilder errorMessage = new StringBuilder(
                        "Error while trying to write the resource attribute ");
                errorMessage.append("AngleRef_TopologicalNode");
                errorMessage.append(" in class ");
                errorMessage.append("TopologicalIsland ");
                errorMessage.append("which ID has been initialized to : ");
                errorMessage.append(getId());
                LOGGER.error(errorMessage.toString());
                LOGGER.error(e.toString(), e);
            }
        }
        }

        if (currentBitset.get(1)) {
      for (TopologicalNode topologicalNodes : this.topologicalNodes){
               try {
                 xmlsw.writeEmptyElement(CIMURI.CIMURI,"TopologicalIsland.TopologicalNodes");
                 xmlsw.writeAttribute(CIMModel.rdfURI, "resource", "#"
                           + topologicalNodes.getId());
               } catch (XMLStreamException e) {
                 StringBuilder errorMessage = new StringBuilder(
                                    "Error while trying to write the reference to ");
                 errorMessage.append("TopologicalIsland ");
                 errorMessage.append("which ID has been initialized to : ");
                 errorMessage.append(getId());
                 errorMessage.append(" in the subset ");
                 errorMessage.append("Topology");
                 LOGGER.error(errorMessage.toString());
                 LOGGER.error(e.toString(), e);
               }
      }
        }

        return;
    }

    /**
     * Utility in charge of creating the message when the class is not
     * consistent within a specific context
     *
     * @param minBitset
     *            bitset describing which CIM attributes of this class have
     *            to be set so that it is consistent within a
     *            specific subset context
     * @return the message explaining what is not consistent
     */
    private String getMessageForConsistency(final BitSet minBitset) {

        StringBuilder message = new StringBuilder(
                "Instance of \"TopologicalIsland\" of id \"");
        message.append(this.getId());
        message.append("\" is not consistent in this context:\n");
        /*
         * XOR and then AND
         * The result is :
         * "1" : has not been set and need to be
         * "0" : has been set or is not mandatory
         */

        BitSet isNotSet = new BitSet(minBitset.length());
        isNotSet.or(minBitset);
        // we create a copy of minBitset
        isNotSet.xor(this.currentBitset);
        isNotSet.and(minBitset);

        if (isNotSet.get(0)) {
            message.append("\t\"AngleRef_TopologicalNode\" needs to be set\n");
        }

        if (isNotSet.get(1)) {
            message.append("\t\"TopologicalNodes\" needs to be set\n");
        }
        return message.toString();
    }

    /**
     * Copy constructor
     * The associations with other objects are not copied
     *
     * @param TopologicalIsland
     *            the reference to the class to copy
     * @return the class constructed
     */
    private TopologicalIsland(final TopologicalIsland otherTopologicalIsland) {
        // TODO : check exception safe
        this.copyBase(otherTopologicalIsland);
    }

   /**
    * Constructor of the class TopologicalIsland
    */
    protected TopologicalIsland() {

        super.subset = Subset.Topology;
        this.minBitsets.put(Subset.StateVariables, new BitSet(2));
        BitSet classBitset = new BitSet(2);
        this.minBitsets.put(Subset.Topology, classBitset);
        this.minBitsets.put(Subset.Equipment, new BitSet(2));
    }



    /**
     * Utility to clear the associations of this class belonging to a
     * specific subset
     *
     * @param subset
     *            the subset from which to clear the associations of this class
     */
    @Override
    protected void clearAssociations(final Subset subset) {

        switch (subset) {
            case StateVariables: {
                super.clearAssociations(subset);
                break;
            }
            case Topology: {
                // reset the Reference
                angleRef_TopologicalNode = null;
                idAngleRef_TopologicalNode = "";
                this.currentBitset.clear(0);
                if (topologicalNodes != null) {
                    topologicalNodes.clear();
                }
                this.currentBitset.clear(1);
                super.clearAssociations(subset);
                break;
            }
            case Equipment: {
                super.clearAssociations(subset);
                break;
            }
            default: // nothing to clear
        }
    }

    /**
     * Utility returning a copy of the "base" of this instance
     * This utility does not copy the associations with other instances
     *
     * @return a clone of this instance
     */
    public TopologicalIsland clone() {
        TopologicalIsland newInstance = new TopologicalIsland(this);
        TopologicalIsland newInstanceSP = newInstance;
        return newInstanceSP;
    }

}



