//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 10:45:35 AM CEST 
//


package eu.itesla_project.iidm.actions_contingencies.xml.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}zones"/>
 *         &lt;element ref="{}contingencies"/>
 *         &lt;element ref="{}elementaryActions"/>
 *         &lt;element ref="{}actionPlans"/>
 *         &lt;element ref="{}actionCtgAssociations"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zones",
    "contingencies",
    "elementaryActions",
    "actionPlans",
    "actionCtgAssociations"
})
@XmlRootElement(name = "actionsContingencies")
public class ActionsContingencies {

    @XmlElement(required = true)
    protected Zones zones;
    @XmlElement(required = true)
    protected Contingencies contingencies;
    @XmlElement(required = true)
    protected ElementaryActions elementaryActions;
    @XmlElement(required = true)
    protected ActionPlans actionPlans;
    @XmlElement(required = true)
    protected ActionCtgAssociations actionCtgAssociations;

    /**
     * Gets the value of the zones property.
     * 
     * @return
     *     possible object is
     *     {@link Zones }
     *     
     */
    public Zones getZones() {
        return zones;
    }

    /**
     * Sets the value of the zones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zones }
     *     
     */
    public void setZones(Zones value) {
        this.zones = value;
    }

    /**
     * Gets the value of the contingencies property.
     * 
     * @return
     *     possible object is
     *     {@link Contingencies }
     *     
     */
    public Contingencies getContingencies() {
        return contingencies;
    }

    /**
     * Sets the value of the contingencies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contingencies }
     *     
     */
    public void setContingencies(Contingencies value) {
        this.contingencies = value;
    }

    /**
     * Gets the value of the elementaryActions property.
     * 
     * @return
     *     possible object is
     *     {@link ElementaryActions }
     *     
     */
    public ElementaryActions getElementaryActions() {
        return elementaryActions;
    }

    /**
     * Sets the value of the elementaryActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementaryActions }
     *     
     */
    public void setElementaryActions(ElementaryActions value) {
        this.elementaryActions = value;
    }

    /**
     * Gets the value of the actionPlans property.
     * 
     * @return
     *     possible object is
     *     {@link ActionPlans }
     *     
     */
    public ActionPlans getActionPlans() {
        return actionPlans;
    }

    /**
     * Sets the value of the actionPlans property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionPlans }
     *     
     */
    public void setActionPlans(ActionPlans value) {
        this.actionPlans = value;
    }

    /**
     * Gets the value of the actionCtgAssociations property.
     * 
     * @return
     *     possible object is
     *     {@link ActionCtgAssociations }
     *     
     */
    public ActionCtgAssociations getActionCtgAssociations() {
        return actionCtgAssociations;
    }

    /**
     * Sets the value of the actionCtgAssociations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionCtgAssociations }
     *     
     */
    public void setActionCtgAssociations(ActionCtgAssociations value) {
        this.actionCtgAssociations = value;
    }

}
