voltageLevel = network.getVoltageLevel("S1VL2")
newNode = voltageLevel.nodeBreakerView.getMaximumNodeIndex() + 1
generator = voltageLevel.newGenerator()
        .setId("GEN2")
        .setNode(newNode)
        .setMinP(0)
        .setMaxP(1000)
        .setVoltageRegulatorOn(true)
        .setTargetV(voltageLevel.nominalV)
        .setTargetP(800)
        .setTargetQ(0)
        .add()

generator.newReactiveCapabilityCurve()
        .beginPoint()
        .setP(200)
        .setMinQ(-350)
        .setMaxQ(350)
        .endPoint()
        .beginPoint()
        .setP(800)
        .setMinQ(-400)
        .setMaxQ(400)
        .endPoint()
        .add()
