name: CI Test

on:
  push:
    branches:
      - 'test/common-workflows'
  pull_request:

permissions: {}

jobs:
  build:
    name: CI Test Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.fork == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout, set up JDK 21, build with Maven and Run SonarCloud analysis
        uses: powsybl/github-ci/setup-java-maven-sonar@ad525ed0fe9a287baf5eea5c569d8c95f0266e79
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_projectKey: 'com.powsybl:powsybl-core'
