name: CI Test

on:
  push:
    branches:
      - 'test/common-workflows'
  pull_request:

permissions: {}

jobs:
  build:
    name: CI Test Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.fork == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout, set up JDK 21, build with Maven and Run SonarCloud analysis
        uses: powsybl/github-ci/setup-java-maven-sonar@804c0dfa9f21d4a35d06b09c655f10386fe77e4a
        with:
          sonar_projectKey: 'com.powsybl:powsybl-core'