name: CI⚡ Test

on:
  push:
    branches:
      - 'test/common-workflows'
  pull_request:

permissions: {}

jobs:
  build:
    name: CI⚡ Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.fork == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup [JDK, Maven build, Sonar]
        uses: powsybl/github-ci/setup-powsybl-dev@c3779beb6e68605d996f3c328f5b350d8c2473cf
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_projectKey: 'com.powsybl:powsybl-core'