name: CI

on:
  push:
    branches:
      - 'main'
      - 'release-v**'
      - 'full-sonar-analysis-**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:

permissions: {}

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: github.event.pull_request.head.repo.fork == false
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Setup [JDK, Maven build, Sonar]
        uses: powsybl/github-ci/setup-powsybl-dev@c44202e128bbdda6696f35135253bd5c514f240f #TODO change version to main after merge in github-ci
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          sonar_projectKey: 'com.powsybl:powsybl-core'
